### ISSUE TITLE
It can make use of SITEID constant

### ISSUE THREAD

**Issue by mudrd8mz** [eberhardt/moodle-local_course_announcement#3]
Currently in `lib.php local_course_announcement_notification()` there is:
```
    $site = isset($SITE) ? $SITE : get_site();
    if (isset($COURSE) && $COURSE->id != $site->id) {
         // ... do the work
    }
```

It might simplify the code if it compared with the {{SITEID}} constant. For example this is what the Forum does:

```
global $PAGE;

if ($PAGE->course->id == SITEID) {
    // do the work
}
```

**Comment by eberhardt** [comment]
You assume that `$PAGE->course` is loaded, but if not there will be a PHP null pointer exception which breaks the rendering of the complete site. So... more like

`if (isset($COURSE) && $COURSE->id != SITEID) {
    // ... do the work
}`

I think there was a reason why I even loaded the `$SITE` object instead of using `SITEID`. It could just be an insane insanity check, but it is also possible that the objects/constants you refer to are not loaded in the early state the plugin renders its messages (try your code on the main page with cache cleared).

**Comment by eberhardt** [comment]
Closing: no issue/fix.
